name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t webpass-test -f ops/containers/be/Dockerfile .

      - name: Run tests in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            -v /tmp/empty-gnupg:/tmp/host-gnupg:ro \
            -w /home/user/app \
            webpass-test \
            uv run -m pytest --cov=.
